// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYH3Ui9emmOxA7pZWEnqi044xv8J03gXo',
    appId: '1:366892240368:web:fd5efc897fee00dabc2135',
    messagingSenderId: '366892240368',
    projectId: 'vona-b7c6c',
    authDomain: 'vona-b7c6c.firebaseapp.com',
    storageBucket: 'vona-b7c6c.firebasestorage.app',
    measurementId: 'G-BXP1YMVWCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0vQ4izlcPwSZ6yqIZ4PAkf0RgxOrAai4',
    appId: '1:366892240368:android:7eb44728d5028955bc2135',
    messagingSenderId: '366892240368',
    projectId: 'vona-b7c6c',
    storageBucket: 'vona-b7c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuPZq5WapA3PFz7In49AwAjF0wrLwAcBU',
    appId: '1:366892240368:ios:b6e70a00ca5edefebc2135',
    messagingSenderId: '366892240368',
    projectId: 'vona-b7c6c',
    storageBucket: 'vona-b7c6c.firebasestorage.app',
    iosBundleId: 'com.vona.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuPZq5WapA3PFz7In49AwAjF0wrLwAcBU',
    appId: '1:366892240368:ios:bbc784b5df63f979bc2135',
    messagingSenderId: '366892240368',
    projectId: 'vona-b7c6c',
    storageBucket: 'vona-b7c6c.firebasestorage.app',
    iosBundleId: 'com.example.vonaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYH3Ui9emmOxA7pZWEnqi044xv8J03gXo',
    appId: '1:366892240368:web:fc3922f7fb47a351bc2135',
    messagingSenderId: '366892240368',
    projectId: 'vona-b7c6c',
    authDomain: 'vona-b7c6c.firebaseapp.com',
    storageBucket: 'vona-b7c6c.firebasestorage.app',
    measurementId: 'G-L9HPLZ7K25',
  );
}
